#pragma once
// Juce config settings

//#define JUCE_ONLY_BUILD_CORE_LIBRARY   1
#define JUCE_QUICKTIME  0
//#define JUCE_FORCE_DEBUG  1
//#define JUCE_LOG_ASSERTIONS  1
#define JUCE_WASAPI 1
#define JUCE_DIRECTSOUND 1
#define JUCE_ASIO  0
//#define JUCE_ALSA  1
#define JUCE_OPENGL  0
#define JUCE_USE_FLAC  0
#define JUCE_USE_OGGVORBIS  0
#define JUCE_USE_CDBURNER  0
//#define JUCE_ENABLE_REPAINT_DEBUGGING  1
//#define JUCE_USE_XINERAMA  1
//#define JUCE_USE_XSHM  1
//#define JUCE_PLUGINHOST_VST  1
//#define JUCE_PLUGINHOST_AU  1
#define JUCE_WEB_BROWSER 0
//#define JUCE_CHECK_MEMORY_LEAKS  1
#define JUCE_CATCH_UNHANDLED_EXCEPTIONS  1
//#define JUCE_STRINGS_ARE_UNICODE  1

#define JUCE_INCLUDE_ZLIB_CODE        1
#define JUCE_INCLUDE_FLAC_CODE        0
#define JUCE_INCLUDE_OGGVORBIS_CODE   0
#define JUCE_INCLUDE_PNGLIB_CODE      1
#define JUCE_INCLUDE_JPEGLIB_CODE     1
