#pragma once
// Juce config settings

//#define JUCE_ONLY_BUILD_CORE_LIBRARY   1
#define JUCE_QUICKTIME  0
//#define JUCE_FORCE_DEBUG  1
//#define JUCE_LOG_ASSERTIONS  1
#define JUCE_ASIO  0
//#define JUCE_ALSA  1
//#define JUCE_OPENGL  1
//#define JUCE_USE_FLAC  1
//#define JUCE_USE_OGGVORBIS  1
//#define JUCE_USE_CDBURNER  1
//#define JUCE_ENABLE_REPAINT_DEBUGGING  1
//#define JUCE_USE_XINERAMA  1
//#define JUCE_USE_XSHM  1
//#define JUCE_PLUGINHOST_VST  1
//#define JUCE_PLUGINHOST_AU  1
//#define JUCE_CHECK_MEMORY_LEAKS  1
//#define JUCE_CATCH_UNHANDLED_EXCEPTIONS  1
//#define JUCE_STRINGS_ARE_UNICODE  1
